services:
  # PostgreSQL
  postgres:
    image: postgres:16.2-alpine
    container_name: hris-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: hris-mongodb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Redis
  redis:
    image: redis:7.2-alpine
    container_name: hris-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: hris-rabbitmq
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # MinIO
  minio:
    image: minio/minio
    container_name: hris-minio
    restart: unless-stopped
    env_file:
      - .env
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  # Go API
  go-api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: hris-go-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/tmp
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

# Volumes
volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  rabbitmq_data:
  minio_data: