FROM golang:1.22-alpine

WORKDIR /app

# InstallAir
RUN go install github.com/cosmtrek/air@v1.52.1

# CopyAllFiles
COPY . .

# TidyDependencies
RUN go mod tidy

# ExecuteAir
CMD ["air", "-c", ".air.toml"]